{{
    config(materialized='incremental',
    unique_key='ORDERID')
}}


SELECT 
ORDERID
,ORDERDATE
,CUSTOMERID
,EMPLOYEEID
,STOREID
,STATUS
,UPDATED_AT
,CURRENT_TIMESTAMP() AS DBT_UPDATED_AT
FROM DEV_T3_INTEGRATION.EMMA.T_ORDERS

{% if is_incremental() %}
WHERE UPDATED_AT >= (SELECT MAX(DBT_UPDATED_AT) FROM DEV_T3_INTEGRATION.EMMA.T_ORDERS_FINAL)
{% endif %}